### ISSUE TITLE
Not working with latest ERPnext version (13)

### ISSUE THREAD

**Issue by satishvijayan** [pipech/frappe-plotly-dash#3]
This is no longer working with ERPnext. would be great if you could make it compatible with the latest ERPnext version 13

I get the following error:
bench get-app dash_integration https://github.com/pipech/frappe-plotly-dash.git

Getting frappe-plotly-dash
$ git clone https://github.com/pipech/frappe-plotly-dash.git  --depth 1 --origin upstream
Cloning into 'frappe-plotly-dash'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 51 (delta 1), reused 39 (delta 0), pack-reused 0
Unpacking objects: 100% (51/51), 6.87 MiB | 2.95 MiB/s, done.

Installing dash_integration
$ ./env/bin/python -m pip install -q -U -e ./apps/dash_integration 
ERROR: Could not find a version that satisfies the requirement dash==1.9.1-daq (from dash-integration) (from versions: 0.17.4, 0.17.5, 0.17.7, 0.17.8rc1, 0.17.8rc2, 0.17.8rc3, 0.18.0, 0.18.1, 0.18.2, 0.18.3rc1, 0.18.3, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.22.0rc1, 0.22.0rc2, 0.22.0, 0.23.1, 0.24.0, 0.24.1rc1, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.26.0, 0.26.1rc1, 0.26.1rc2, 0.26.1rc3, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.26.5, 0.26.6, 0.27.0rc1, 0.27.0rc2, 0.27.0rc3, 0.27.0rc4, 0.27.0rc5, 0.27.0rc6, 0.27.0rc7, 0.27.0rc8, 0.27.0rc9, 0.27.0, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.28.7, 0.29.0rc1, 0.29.0rc2, 0.29.0rc3, 0.29.0rc4, 0.29.0rc5, 0.29.0rc6, 0.29rc7, 0.29.0rc8, 0.29.0, 0.30.0rc1, 0.30.0rc2, 0.30.0rc3, 0.30.0rc4, 0.30.0rc5, 0.30.0, 0.31.0rc1, 0.31.0rc2, 0.31.0, 0.31.1, 0.32.0rc1, 0.32.0rc2, 0.32.0, 0.32.1, 0.32.2, 0.34.0, 0.35.0rc1, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.36.0rc1, 0.36.0, 0.37.0rc1, 0.37.0rc2, 0.37.0, 0.38.0rc1, 0.38.0, 0.39.0, 0.40.0rc1, 0.40.0, 0.41.0, 0.42.0, 0.43.0rc1, 0.43.0rc2, 0.43.0rc3, 0.43.0, 1.0.0a1, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 1.14.0, 1.15.0, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.18.0, 1.18.1, 1.19.0, 1.20.0)
ERROR: No matching distribution found for dash==1.9.1-daq
$ bench build --app dash_integration
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/srv/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/srv/bench/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/srv/bench/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/srv/bench/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/bench/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/bench/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/bench/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/srv/bench/frappe-bench/apps/frappe/frappe/commands/utils.py", line 26, in build
    frappe.init('')
  File "/srv/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 202, in init
    setup_module_map()
  File "/srv/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in setup_module_map
    for module in get_module_list(app):
  File "/srv/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 975, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/srv/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 933, in get_module
    return importlib.import_module(modulename)
  File "/srv/bench/frappe-bench/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dash_integration'

**Comment by satishvijayan** [comment]
Thanks, it is installing now!

I get the following warnings/errors. But it seems to install. Will continue trying and let you know how it goes. 

Thanks again!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`


Getting frappe-plotly-dash
$ git clone https://github.com/pipech/frappe-plotly-dash.git  --depth 1 --origin upstream
Cloning into 'frappe-plotly-dash'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 51 (delta 1), reused 39 (delta 0), pack-reused 0
Unpacking objects: 100% (51/51), 6.87 MiB | 6.27 MiB/s, done.

Installing dash_integration
$ ./env/bin/python -m pip install -q -U -e ./apps/dash_integration 
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_c432f5c2378a4eac8585db28225a7493/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_c432f5c2378a4eac8585db28225a7493/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lyhjhku7
         cwd: /tmp/pip-install-svuze8lh/frappe_c432f5c2378a4eac8585db28225a7493/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_c432f5c2378a4eac8585db28225a7493/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_c432f5c2378a4eac8585db28225a7493/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4c/d3/73da0e17271031bacd2c585588026701ae5934329264db575ad989cc9ce3/frappe-2.1.4.tar.gz#sha256=6ca5313aceb1212f8044efc15ccf03461b2c85644e33716616a02a1fe2bb5c1f (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_6c69e4100eff42d7802c88fca00ce7b4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_6c69e4100eff42d7802c88fca00ce7b4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-174jw5su
         cwd: /tmp/pip-install-svuze8lh/frappe_6c69e4100eff42d7802c88fca00ce7b4/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_6c69e4100eff42d7802c88fca00ce7b4/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_6c69e4100eff42d7802c88fca00ce7b4/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/15/33/82337920a2b80992eda2fbe08d4e34b47e6f3f23386488716b35ca7b43cc/frappe-2.1.3.tar.gz#sha256=dbd6b484438e29e193c1110fc3db0a3ec19247265353f7f1cf76aaa88667eb4c (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_2f4cb0caac354afaaf70bdf2100dfd01/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_2f4cb0caac354afaaf70bdf2100dfd01/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ko_o51be
         cwd: /tmp/pip-install-svuze8lh/frappe_2f4cb0caac354afaaf70bdf2100dfd01/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_2f4cb0caac354afaaf70bdf2100dfd01/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_2f4cb0caac354afaaf70bdf2100dfd01/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/34/cb/197c1aa6cc35ecfe60f9ba88f59897ab43853ef24daf9a9582623c09ded8/frappe-2.1.1.tar.gz#sha256=336825156c77442495e4907666e5717b6f5145caddaed5084ed617967c2059f8 (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_29dca1121d1c4dfd8488a6c3561f30bf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_29dca1121d1c4dfd8488a6c3561f30bf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ndd4rgif
         cwd: /tmp/pip-install-svuze8lh/frappe_29dca1121d1c4dfd8488a6c3561f30bf/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_29dca1121d1c4dfd8488a6c3561f30bf/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_29dca1121d1c4dfd8488a6c3561f30bf/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/83/9b/731b47beb7e955966c3b6dc91b1aca3476905a15e50e84501ddf4180d932/frappe-2.1.0.tar.gz#sha256=972ca33b15391738614aca1d1eecc72aa5ea65cb22bd5a61007ae529dc3c8fd9 (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_fcb237432cb7412e9db22005febf0467/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_fcb237432cb7412e9db22005febf0467/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dbyrow7t
         cwd: /tmp/pip-install-svuze8lh/frappe_fcb237432cb7412e9db22005febf0467/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_fcb237432cb7412e9db22005febf0467/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_fcb237432cb7412e9db22005febf0467/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/52/22/eca999b4ee5c0b5375f20251855e7f41ff34926e9991a798e4cb418d0487/frappe-2.0.4.tar.gz#sha256=c358596c17498f541ba378c1e1ae85c0b618b9bfc806ee959d7b9110ec68ff11 (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_6e73bd08ae0e452aa828daa4d8fa30da/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_6e73bd08ae0e452aa828daa4d8fa30da/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-us4s6aag
         cwd: /tmp/pip-install-svuze8lh/frappe_6e73bd08ae0e452aa828daa4d8fa30da/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_6e73bd08ae0e452aa828daa4d8fa30da/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_6e73bd08ae0e452aa828daa4d8fa30da/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/ff/eca36111b79ab75564a63cf4a13b5c0dc9f61a73ad946dbe7317490eb7c7/frappe-2.0.3.tar.gz#sha256=196b6ee44719dc4d292ff0b68b186ad1cc8524026384f9eee0ac55629562cf04 (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_3b4dc1d65f024b8fb15e82bbdffe6e09/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_3b4dc1d65f024b8fb15e82bbdffe6e09/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fqr4lkms
         cwd: /tmp/pip-install-svuze8lh/frappe_3b4dc1d65f024b8fb15e82bbdffe6e09/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_3b4dc1d65f024b8fb15e82bbdffe6e09/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_3b4dc1d65f024b8fb15e82bbdffe6e09/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/00/af/5f156782a137430a35f3115988edf37b383778ec4487a3512b3308a3a7be/frappe-2.0.2.tar.gz#sha256=b9abaf1a865b3acbf49a27f6cb11217b4b980da631e623a0792c4babda9df951 (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_27904272706c4f10a0a75fa3cc3300d7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_27904272706c4f10a0a75fa3cc3300d7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5c4_08nr
         cwd: /tmp/pip-install-svuze8lh/frappe_27904272706c4f10a0a75fa3cc3300d7/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_27904272706c4f10a0a75fa3cc3300d7/setup.py", line 7, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_27904272706c4f10a0a75fa3cc3300d7/setup.py", line 9, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f6/9d/658c5c54186e860bde0a3c1425bbd65b9d31e0bc212e780520746cd4f9ce/frappe-2.0.1.tar.gz#sha256=7ce96e27fd85398cc198fd1b3273f729f7d92abce8adb25db5b0bd30f080105e (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /srv/bench/frappe-bench/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-svuze8lh/frappe_46fcfb5b47974957976d79debb590625/setup.py'"'"'; __file__='"'"'/tmp/pip-install-svuze8lh/frappe_46fcfb5b47974957976d79debb590625/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2kpf7n5a
         cwd: /tmp/pip-install-svuze8lh/frappe_46fcfb5b47974957976d79debb590625/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-svuze8lh/frappe_46fcfb5b47974957976d79debb590625/setup.py", line 7, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-svuze8lh/frappe_46fcfb5b47974957976d79debb590625/setup.py", line 9, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ea/ca/e79fefd0cb7a401a29b2d7b43d47398a8ae94f1845242670d32ff18dccf9/frappe-2.0.tar.gz#sha256=c1d96f156824ad0894548ac05101555ed59a0250e22bd2b1294ce9e92f188e98 (from https://pypi.org/simple/frappe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/42/ca/a84c8718940dc5a59398bb5c1fd2050a0007fabc4c00e1e70ad642b7d3c3/Flask-Compress-1.2.0.1.tar.gz#sha256=ebd6928caf0ea3e2d422275c1ed3e41742488174ede5bd811bcc476964e20706 (from https://pypi.org/simple/flask-compress/). Requested flask-compress from https://files.pythonhosted.org/packages/42/ca/a84c8718940dc5a59398bb5c1fd2050a0007fabc4c00e1e70ad642b7d3c3/Flask-Compress-1.2.0.1.tar.gz#sha256=ebd6928caf0ea3e2d422275c1ed3e41742488174ede5bd811bcc476964e20706 (from dash==1.9.1->dash-integration==0.0.1) has inconsistent version: filename has '1.2.0.1', but metadata has '1.2.0'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/srv/bench/frappe-bench/env/bin/python -m pip install --upgrade pip' command.
$ bench build --app dash_integration
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

yarn run v1.22.4
$ FRAPPE_ENV=production node rollup/build.js --app dash_integration
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js
Done in 1.29s.
$ supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
